### ISSUE TITLE
[RFC] Initial release

### ISSUE THREAD

**Issue by shannonmoeller** [prettier/stylelint-config-prettier-scss#1]
Initial beta release. Forked from `stylelint-config-prettier` based on prettier/stylelint-config-prettier#127. Looking for feedback, beta testers, and rule recommendations.

**Comment by riddla** [comment]
This works me, as I had to disable `scss/operator-no-newline-after` manually before.
Thanks a lot!

**Comment by chalkygames123** [comment]
Cool. Though I don't have time right now, I hope to make some progress on the "overrides" thing soon.

**Comment by shannonmoeller** [comment]
@chalkygames123 I think that's a great idea for the long run, but I'm not quite ready to drop backwards compatibility with versions of stylelint older than 14 yet, so no rush.

**Comment by Plondrein** [comment]
works for me :) thanks for this repo!

EDIT: I only wonder whether **scss/dollar-variable-empty-line-before** rule should also be added (maybe not?)

**Comment by shannonmoeller** [comment]
@Plondrein Is it possible to configure `scss/dollar-variable-empty-line-before` in a way that conflicts with prettier? Seems like the rule might work okay in addition to prettier?

**Comment by Plondrein** [comment]
Yes you're right - it doesn't conflict, yet it's strictly formatting rule and for formatting I'd like to rely only on prettier - but I see my point of view might be invalid as we here are only turning off conflicts

**Comment by Airkro** [comment]
Please exclude useless files when publishing.

**Comment by rdebeasi** [comment]
This config works well for me - thank you!!

@Airkro I agree; it would be nice to exclude tests and other files that aren't useful to the consumer. 
The publishing behavior seems to originate from the [`stylelint-config-prettier`](https://github.com/prettier/stylelint-config-prettier) package, so it may be worth filing a separate issue there.

```
stylelint-config-prettier-scss % ls
bin		node_modules	readme.md	test
license		package.json	src

stylelint-config-prettier % ls
bin		node_modules	readme.md	test
license		package.json	src
```
