### ISSUE TITLE
Peer Dependency issue

### ISSUE THREAD

**Issue by drew0530** [prettier/stylelint-config-prettier-scss#11]
![image](https://github.com/prettier/stylelint-config-prettier-scss/assets/25624473/32472326-f383-48c6-8bc4-6bece46107ce)

This package is not up to date with the latest version of stylelint.

**Comment by elwayman02** [comment]
@drew0530 can you explain the issue you're seeing in more detail? The error in your screenshot looks like it's coming from `stylelint-config-prettier` (a deprecated package) requiring a lower version of stylelint, which has nothing to do with this package, `stylelint-config-prettier-scss`.

**Comment by drew0530** [comment]
It appears to me that stylelint-config-prettier-scss requires version 15.0.0, and I have 15.10.0 installed, which is providing me a warning. 
![image](https://github.com/prettier/stylelint-config-prettier-scss/assets/25624473/25d19469-612e-46ff-a4e0-106e14a12479)

![image](https://github.com/prettier/stylelint-config-prettier-scss/assets/25624473/69f821d2-0bbf-4f82-a2b9-a4ac809f7936)

![image](https://github.com/prettier/stylelint-config-prettier-scss/assets/25624473/ae31adcc-3479-4736-a05c-c01e20df6ed0)

Sorry for the ambiguity.

**Comment by elwayman02** [comment]
@drew0530 that is not an error. This package requires any version of stylelint >=15, which is valid in your case. The screenshot you shared shows the error I described above. Do you have `stylelint-config-prettier` installed? If so, remove it and the error will go away.

**Comment by drew0530** [comment]
That solved the issue, thank you.
