### ISSUE TITLE
TypeError: stylelint.createLinter(...).getConfigForFile is not a function

### ISSUE THREAD

**Issue by stephen-liu-fipo** [prettier/stylelint-config-prettier-scss#3]
https://github.com/prettier/stylelint-config-prettier-scss#cli-helper-tool

**Comment by misdreavus79** [comment]
I take it these two issues are related? https://github.com/prettier/stylelint-config-prettier/issues/134

**Comment by stephen-liu-fipo** [comment]
> I take it these two issues are related? [prettier/stylelint-config-prettier#134](https://github.com/prettier/stylelint-config-prettier/issues/134)

yes

**Comment by elwayman02** [comment]
I believe #6 fixes this issue
